### ISSUE TITLE
Desig Files available, too?

### ISSUE THREAD

**Issue by beniroquai** [ImperialCollegeLondon/openFrame#1]
Hey @SK-UK, great project! I really appreciate this!! I have downloaded the STP files and tried to interact with them a bit. I was wondering if you had the modifiable designfiles as well. I use inventor, but typically one can convert from e.g. Solidworks to Iventor or Fusion360. Thanks a lot! :-)

**Comment by pmwf** [comment]
Hi Benedict,

Good to catch up with you at Janelia.

Sunil will have to answer this. I am not clear about limitations of CAD files.

Best wishes,

Paul

(If I email you out of normal working hours, I would not expect any response before your next working day)

From: Benedict Diederich ***@***.***>
Sent: Wednesday, May 8, 2024 12:57 PM
To: ImperialCollegeLondon/openFrame ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ImperialCollegeLondon/openFrame] Desig Files available, too? (Issue #1)


Hey @SK-UK<https://github.com/SK-UK>, great project! I really appreciate this!! I have downloaded the STP files and tried to interact with them a bit. I was wondering if you had the modifiable designfiles as well. I use inventor, but typically one can convert from e.g. Solidworks to Iventor or Fusion360. Thanks a lot! :-)

**Comment by SK-UK** [comment]
Hi Benedict,

There is a Work-In-Progress effort to make designs for all the components in OnShape that can be found here:
https://cad.onshape.com/documents/3b48c6a8511b1b43c7bff627/w/7d6b863b3b5475129e35c451/e/34bea7accd4a352a9b473443

Once these designs are complete on an open platform, they'll be linked from this repo. For now though, please double-check anything on OnShape against the files here before using it!

Regards,
Sunil

**Comment by beniroquai** [comment]
Thanks a lot! I will catch up with the printer once I'm back in Germany :-)
